[discord]
token = "main_bot_token"

[github]
url = "https://github.com/codecat/reddit-radio"
url = "https://github.com/KurzaCationer/reddit-radio"
dest = "reddit-radio"
safefiles = ["config.toml", "reddit-radio", "node_modules", "start.bat"]

[[commands]]
prefix = "Qdnp"
aliases = [ "Qdcp" ]

[[commands]]
prefix = "Qdprev"

[[commands]]
prefix = "Qdnext"

[voice]
passes = 2
bitrate = 44100

[soundcloud]
client_id = "soundcloud_client_id"

[[radios]]
token = "radio_bot_1_token"
channel = "330121740758024193"
name = "Q-Dance Radio"
url = "http://audio.true.nl/qdance-hard"
